### ISSUE TITLE
Required `git_push_flags` ?

### ISSUE THREAD

**Issue by supcik** [dokku/github-action#1]
## Description of problem

I just discovered this repo and wanted to try. It works for me, but only if I define the `git_push_flags` (e.g. with '-v'). I also noticed that this field is actually _required_ in the `action.yml` file :

```
  git_push_flags:
    description: "The dokku app's git repository url (in SSH format)"
    required: true
```

Is this supposed to be so ? In most examples the `git_push_flags` is not used.

**Comment by josegonzalez** [comment]
The input names were incorrect. You should be able to ignore that flag now :)
