### ISSUE TITLE
[Question] How can use this with monorepos?

### ISSUE THREAD

**Issue by rigobcastro** [dokku/github-action#13]
I have a monorepo and I want to deploy only one package. I didn't see any parameter to set the subfolder or working directory. 

Do you have some approach to work with monorepos or subfolder?

**Comment by josegonzalez** [comment]
Dokku does not currently support monorepos. The next version - 0.25 - will support them. To follow the feature work, see https://github.com/dokku/dokku/pull/4502 .

If you'd like an ETA or want the work to be completed faster, consider [sponsoring the work](https://github.com/dokku/.github/blob/master/SPONSORING.md).

Hope that answers your question.

**Comment by johnniehard** [comment]
I think this should be doable with [dokku-monorepo](https://github.com/notpushkin/dokku-monorepo) and a separate gh-action for each app. Only caveat I can think of up front is that all of your applications will be deployed every time you push something to gh.

I'll try it and report back.

**Comment by johnniehard** [comment]
Tried it, works fine.
