### ISSUE TITLE
Deploy another branch to dokku than master

### ISSUE THREAD

**Issue by domvo** [dokku/github-action#16]
I would like to use this action to deploy another branch than the master branch of my repository. In fact, I have a workflow that can be triggered manually and accepts a branch name as an input. Is there a way to achieve this with this action? I can't seem to make it work.

Thanks!

**Comment by josegonzalez** [comment]
Apologies for the late reply. There is an example workflow for specifying a custom branch [here](https://github.com/dokku/github-action/blob/master/example-workflows/custom-deploy-branch.yml).

**Comment by josegonzalez** [comment]
@sardaukar if you're seeing an issue with the documentation, please open a new ticket. The response here was given almost 2 years ago, and there is probably something else going on with whatever issue you are seeing.
