### ISSUE TITLE
Pre-deploy action location clarification

### ISSUE THREAD

**Issue by fobos531** [dokku/github-action#50]
## Description of problem

This is more of a question. I need to run a script before the deploy starts, and I see there is an example of the pre-deploy action. It is mentioned that the file should be located at `bin/ci-pre-deploy`. However, I'm not sure where exactly should the `bin` folder be located - should it be located at the root directory of my app? Any clarification regarding this would be greatly appreciated.

Thanks!

**Comment by josegonzalez** [comment]
Yes, that is correct
