### ISSUE TITLE
Issues with GitHub Actions Using IPv6 to Connect to Dokku

### ISSUE THREAD

**Issue by matiasAS** [dokku/github-action#75]
Description of problem:
I am attempting to use GitHub Actions to deploy an application to a Dokku host using an IPv6 address. Despite being able to connect directly via SSH using the IPv6 address from another server, I encounter issues when GitHub Actions tries to establish the connection.

How reproducible:
Every time GitHub Actions runs.

Steps to Reproduce:

Set up a GitHub Action workflow with the Dokku GitHub action.
Configure the git_remote_url to use an IPv6 address.
Run the workflow.
Actual Results:
The GitHub Action fails to resolve the IPv6 address, resulting in connection failures.
getaddrinfo [2600:....]: Name does not resolve

Expected Results:
The GitHub Action should successfully connect to the Dokku host using the provided IPv6 address and deploy the application.

Environment Information:

GitHub Actions workflow is set up as per the Dokku GitHub action documentation.
The Dokku host is configured to accept IPv6 connections.
Additional information:

I can successfully connect to the Dokku host using the IPv6 address from a different server using SSH.
Here is the relevant part of my GitHub Actions configuration:

- name: Deploy to Dokku
  uses: dokku/github-action@master
  with:
    git_remote_url: 'ssh://dokku@[IPv6_ADDRESS]/APP_NAME'
    ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

The IPv6 address works as expected elsewhere, so it seems to be an issue specific to how GitHub Actions or the Dokku GitHub Action handles IPv6 addresses.
Any guidance on how to resolve this issue or any workarounds would be greatly appreciated. If additional information is needed, I am happy to provide it.

**Comment by josegonzalez** [comment]
Can you show the entire output of the action run?

**Comment by josegonzalez** [comment]
Closing this ticket for now as there hasn't been any follow-up. If folks are still having this issue, please provide more details as to how I can replicate the problem.
