### ISSUE TITLE
Is there a possibility to do all building in github and push built artifacts to dokku?

### ISSUE THREAD

**Issue by j-a-h-i-r** [dokku/github-action#76]
I'm just curious if it would be possible to let all the build related tasks happen in github actions? One of the most common issues I faced is trying to build an app on a low memory VPS. The memory issue can be avoided if the heavy lifting parts related to build can be offloaded to run on github actions.

**Comment by josegonzalez** [comment]
If you push your image to a registry, we have an example [here](https://github.com/dokku/github-action/blob/master/example-workflows/build-and-deploy.yml) on how to do that.
