### ISSUE TITLE
Host key verification failed.

### ISSUE THREAD

**Issue by robinwo** [dokku/github-action#8]
Hey, I keep getting the "Host key verification failed." error.

What I've done so far:
- On Github, configured repo secret SSH_HOST_KEY (/root/.ssh/id_rsa.pub)
- On the server, created a new SSH key (/home/dokku/.ssh/deploy_key)
- On the server, added this SSH key to the SSH Agent
- On Github, configured repo secret SSH_PRIVATE_KEY (/home/dokku/.ssh/deploy_key)
- Updated the Action yaml file to use these variables & SSH as dokku user (as in the example)
- On Github, also configured repo 'Deploy key', taking the public key from the server (/home/dokku/.ssh/deploy_key.pub), following this [doc](https://docs.github.com/en/developers/overview/managing-deploy-keys)
- On the server, added the SSH deploy key also to dokku via 'dokku ssh-keys:add deploy /home/dokku/.ssh/deploy_key.pub'

Unfortunately, keep getting the following result:
What am I doing wrong?

```
Setting up SSH Key

Adding SSH_HOST_KEY to known_hosts

Adding SSH Key to ssh-agent
Agent pid 17
Identity added: /root/.ssh/id_rsa (root@server.hostname)

Pushing to Dokku Host
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

And my yaml file:
```
# deploy to dokku
name: 'deploy'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@server.hostname:22/appname'
          ssh_host_key: ${{ secrets.SSH_HOST_KEY }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
```

**Comment by josegonzalez** [comment]
From the [docs](https://github.com/dokku/github-action#examples):

> The SSH_HOST_KEY value can be retrieved by calling `ssh-keyscan -t rsa $HOST`, where `$HOST` is the Dokku server's hostname.

I think you are setting the wrong value there, or maybe not understanding what host keys verification does (it verifies the host is exactly the one you expect to talk to without any MITM attacks). Try either setting the correct value or dropping usage and your deploys should start working again,

**Comment by robinwo** [comment]
Ok reason why I added this key in the config, is because without this setting, I was getting a slight different error - permissions issue.

See below:
```
Setting up SSH Key

Generating SSH_HOST_KEY from ssh-keyscan against server.hostname:22
# server.hostname:22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
# server.hostname:22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
# server.hostname:22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
# server.hostname:22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
# server.hostname:22 SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1

Adding SSH Key to ssh-agent
Agent pid 24
Identity added: /root/.ssh/id_rsa (root@server.hostname)

Pushing to Dokku Host
Warning: Permanently added the ECDSA host key for IP address '188.166.11.11' to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
dokku@server.hostname: Permission denied (publickey,password).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Any clue?

**Comment by badsyntax** [comment]
you need to change `appname` to match the name of the app you're deploying.

**Comment by robinwo** [comment]
Yep that’s done - for sake of simplicity using appname & server.hostname in this example.

**Comment by josegonzalez** [comment]
Can you show the exact value you are setting for `git_remote_url`? It seems like the app name isn't being parsed properly, so I wonder if something else is up.

**Comment by robinwo** [comment]
Jup, find below the unmasked file:

`# deploy to dokku
name: 'deploy'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@server3.rbnhd.nl:22/kamersoc-master.git'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}`

**Comment by danialeresbar** [comment]
I have the same problem with appname (for my case 'carpa') :(

**Comment by josegonzalez** [comment]
@danialeresbar can you post your exact config (please don't redact anything) as well as the exact output that config is giving you?

**Comment by danialeresbar** [comment]
Hi @josegonzalez 
My config is:

![yml](https://user-images.githubusercontent.com/36459449/108973309-30059480-7652-11eb-903b-db4c181b24ec.PNG)


My output is:

![Deploy](https://user-images.githubusercontent.com/36459449/108973119-00ef2300-7652-11eb-9e61-d4731e0b1342.PNG)

My dokku apss:

![Apps](https://user-images.githubusercontent.com/36459449/108973348-3bf15680-7652-11eb-8b28-4c9b5d9569a1.PNG)

**Comment by danialeresbar** [comment]
I am sure that the key is configured correctly because it is the same that I use to deploy with

gi push <my-dokku-remote> <my-branch>: master

When I deploy with git there is no problem

I don't understand why I get the '/' character as a prefix of the app name. Is there any way to avoid it?

**Comment by josegonzalez** [comment]
Yeah that seems like the bug in question. Can you copy-paste the exact config here (not a screenshot) of that workflow?

**Comment by danialeresbar** [comment]
Ok, here it go:

name: CARPA CI/CD

on:
  push:
    branches: [master, develop]
  pull_request:
    branches:  [master, develop]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@157.230.57.158:22/carpa'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

**Comment by josegonzalez** [comment]
Great thanks, I'll try and replicate with this.

**Comment by danialeresbar** [comment]
@josegonzalez Any progress?

**Comment by josegonzalez** [comment]
No it was like 4am when I posted but I’ll have time this week at some point, maybe today

**Comment by danialeresbar** [comment]
Ok thanks a lot :D

**Comment by danjac** [comment]
I'm seeing a similar issue: given this git_remote_url:

`git_remote_url: 'ssh://dokku@<ipaddr>:22/appname'`

I get this error:
```

Pushing to Dokku Host
FAILED: App name must begin with lowercase alphanumeric character, and cannot include uppercase characters or colons
fatal: Could not read from remote repository.
```

**Comment by bobwhitelock** [comment]
I just ran into this issue as well:

```
fatal: '/appname' does not appear to be a git repository
fatal: Could not read from remote repository.
```

It seems like when using the SSH form for Git URLs, it will look for the repo at an absolute path (see https://stackoverflow.com/questions/14348874/git-repository-url-ssh-syntax-without-absolute-path), hence this error message as Dokku will by default clone repos relative to the Dokku user's home directory, rather than the root directory.

When I specified `git_remote_url` like `git_remote_url: 'ssh://dokku@server.hostname:22/~/appname'`, rather than `git_remote_url: 'ssh://dokku@server.hostname:22/appname'`, then this worked fine for me. Possibly the documentation/examples should indicate this?

**Comment by robinwo** [comment]
This solved the issue for me! Thanks @bobwhitelock

**Comment by justinalexandershaw** [comment]
> When I specified git_remote_url like git_remote_url: 'ssh://dokku@server.hostname:22/~/appname', rather than git_remote_url: 'ssh://dokku@server.hostname:22/appname', then this worked fine for me.

Had the same issue, and this worked for me as well.

**Comment by danjac** [comment]
I've tried both 

`git_remote_url: 'ssh://dokku@server.hostname:22/~/appname'`

and 

`git_remote_url: 'ssh://dokku@server.hostname:22/appname'`

with a working Dokku install and both fail with 

```Pushing to Dokku Host
fatal: not a git repository (or any parent up to mount point /github)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

Running the usual git push dokku command works.

**Comment by josegonzalez** [comment]
@danjac i think your issue is different, mind filing a separate issue?

**Comment by josegonzalez** [comment]
@justinalexandershaw mind posting your complete workflow file? Additionally, if you push from a local install, what does your remote look like?

**Comment by justinalexandershaw** [comment]
@josegonzalez sure!

**Comment by danjac** [comment]
@josegonzalez it was a mistake on my part: needed to clone repo in previous step:

```
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
    - name: Push to Dokku
      uses: dokku/github-action@master
      ...
```

Plain **git_remote_url** i.e. `/appname` not `~/appname `worked fine.

**Comment by justinalexandershaw** [comment]
Now that I think of it, I remember our deploy pipeline working fine without the `~/appname` in our original build. We changed cloud providers recently and `/appname` worked on the old one and failed on the new one (switched from a bare-metal host to AWS EC2). The fix for EC2 was to add the tilde. Maybe that will help someone?

**Comment by josegonzalez** [comment]
@robinwo @bobwhitelock @danialeresbar you three wouldn't happen to also be on ec2, would you?

@justinalexandershaw how did you install on EC2?

**Comment by justinalexandershaw** [comment]
@josegonzalez Nothing special about the install iirc. Just followed the docs: https://dokku.com/docs/getting-started/installation/#1-install-dokku

**Comment by josegonzalez** [comment]
Mind posting the output of `dokku report`?

**Comment by justinalexandershaw** [comment]
<details>
<summary>click me</summary>
<br>
<pre>
-----> uname: Linux webserver 5.4.0-1045-aws #47-Ubuntu SMP Tue Apr 13 07:02:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

-----> memory:
                     total        used        free      shared  buff/cache   available
       Mem:           7666         390        4602           1        2672        7009
       Swap:             0           0           0
-----> docker version:
       Client: Docker Engine - Community
        Version:           20.10.7
        API version:       1.41
        Go version:        go1.13.15
        Git commit:        f0df350
        Built:             Wed Jun  2 11:56:38 2021
        OS/Arch:           linux/amd64
        Context:           default
        Experimental:      true

       Server: Docker Engine - Community
        Engine:
         Version:          20.10.7
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.13.15
         Git commit:       b0f5bc3
         Built:            Wed Jun  2 11:54:50 2021
         OS/Arch:          linux/amd64
         Experimental:     false
        containerd:
         Version:          1.4.6
         GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
        runc:
         Version:          1.0.0-rc95
         GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info:
       Client:
        Context:    default
WARNING: No swap limit support
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

       Server:
        Containers: 1
         Running: 1
         Paused: 0
         Stopped: 0
        Images: 5
        Server Version: 20.10.7
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
        runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 5.4.0-1045-aws
        Operating System: Ubuntu 20.04.2 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 2
        Total Memory: 7.487GiB
        Name: webserver
        ID: GERX:YFC3:5C6B:Z24Q:QDOD:5X5I:QTUI:R5EU:PPTR:6OUE:CMU6:6Z2R
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: false
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false

-----> git version: git version 2.25.1
-----> sigil version: 0.6.0
-----> herokuish version:
       herokuish: 0.5.28
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v228
         heroku-buildpack-nodejs    v185
         heroku-buildpack-clojure   v87
         heroku-buildpack-python    v196
         heroku-buildpack-java      v69
         heroku-buildpack-gradle    v35
         heroku-buildpack-scala     v90
         heroku-buildpack-play      v26
         heroku-buildpack-php       v194
         heroku-buildpack-go        v153
         buildpack-nginx            v14
         buildpack-null             v3
-----> dokku version: dokku version 0.24.10
-----> plugn version: plugn: 0.6.1
-----> dokku plugins:
         00_dokku-standard    0.24.10 enabled    dokku core standard plugin
         20_events            0.24.10 enabled    dokku core events logging plugin
         app-json             0.24.10 enabled    dokku core app-json plugin
         apps                 0.24.10 enabled    dokku core apps plugin
         builder              0.24.10 enabled    dokku core builder plugin
         builder-dockerfile   0.24.10 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.24.10 enabled    dokku core builder-herokuish plugin
         builder-pack         0.24.10 enabled    dokku core builder-pack plugin
         buildpacks           0.24.10 enabled    dokku core buildpacks plugin
         certs                0.24.10 enabled    dokku core certificate management plugin
         checks               0.24.10 enabled    dokku core checks plugin
         common               0.24.10 enabled    dokku core common plugin
         config               0.24.10 enabled    dokku core config plugin
         cron                 0.24.10 enabled    dokku core cron plugin
         docker-options       0.24.10 enabled    dokku core docker-options plugin
         domains              0.24.10 enabled    dokku core domains plugin
         enter                0.24.10 enabled    dokku core enter plugin
         git                  0.24.10 enabled    dokku core git plugin
         letsencrypt          0.11.9 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.24.10 enabled    dokku core logs plugin
         network              0.24.10 enabled    dokku core network plugin
         nginx-vhosts         0.24.10 enabled    dokku core nginx-vhosts plugin
         plugin               0.24.10 enabled    dokku core plugin plugin
         proxy                0.24.10 enabled    dokku core proxy plugin
         ps                   0.24.10 enabled    dokku core ps plugin
         repo                 0.24.10 enabled    dokku core repo plugin
         resource             0.24.10 enabled    dokku core resource plugin
         scheduler-docker-local 0.24.10 enabled    dokku core scheduler-docker-local plugin
         shell                0.24.10 enabled    dokku core shell plugin
         ssh-keys             0.24.10 enabled    dokku core ssh-keys plugin
         storage              0.24.10 enabled    dokku core storage plugin
         tags                 0.24.10 enabled    dokku core tags plugin
         tar                  0.24.10 enabled    dokku core tar plugin
         trace                0.24.10 enabled    dokku core trace plugin
</pre>
</details>

**Comment by bobwhitelock** [comment]
> @robinwo @bobwhitelock @danialeresbar you three wouldn't happen to also be on ec2, would you?

No, I'm using Linode

**Comment by robinwo** [comment]
Me neither, digitalocean

**Comment by josegonzalez** [comment]
I wonder if this is 20.04 only and thats why I'm not seeing it...

**Comment by IgnisDa** [comment]
Adding `~` before the `/appname` worked for me too. I am using a Digital Ocean server, with the dokku droplet.

**Comment by adrianthedev** [comment]
I have the following config file and works fine. I fiddled like crazy with the config until I got it working

```yaml
---
name: 'deploy'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: master
          git_remote_url: 'ssh://dokku@avohq.io:22/avohq'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
```

**Comment by cromulus** [comment]
I'm having this issue as well. Neither `/~/appname` nor `/appname` works.

**Comment by josegonzalez** [comment]
I've added a `trace` mode option to this action. If someone having this issue can post the output of trying the `git_remote_url` in the format `ssh://dokku@dokku.myhost.ca:22/appname` and set `trace: 1` in their job step, that would be excellent. My guess is that somehow the parsing we do of the host is broken for some reason.

**Comment by JKingas** [comment]
@josegonzalez 
I tried first time Dokku. And trying via GitHub Actions and got same issue. It is not clear who is changing the directory to `/github` for ssh. For direct push via ssh it works well.

Logs with `trace: 1`

<details>
<summary>Click me</summary>

```
Run dokku/github-action@v1.4.0
  with:
    git_remote_url: ssh://dokku@dokku.mydomain.com:22/myapp-test
    ssh_host_key: ***
    ssh_private_key: ***
    trace: 1
    branch: master
    command: deploy
/usr/bin/docker run --name ac4e1e14194c3ba25c8d6c8bd6140d_d36f0d --label 765292 --workdir /github/workspace --rm -e "INPUT_GIT_REMOTE_URL" -e "INPUT_SSH_HOST_KEY" -e "INPUT_SSH_PRIVATE_KEY" -e "INPUT_TRACE" -e "INPUT_BRANCH" -e "INPUT_CI_BRANCH_NAME" -e "INPUT_CI_COMMIT" -e "INPUT_COMMAND" -e "INPUT_DEPLOY_DOCKER_IMAGE" -e "INPUT_DEPLOY_USER_NAME" -e "INPUT_DEPLOY_USER_EMAIL" -e "INPUT_GIT_PUSH_FLAGS" -e "INPUT_REVIEW_APP_NAME" -e "BRANCH" -e "CI_BRANCH_NAME" -e "CI_COMMIT" -e "COMMAND" -e "DEPLOY_DOCKER_IMAGE" -e "DEPLOY_USER_NAME" -e "DEPLOY_USER_EMAIL" -e "GIT_PUSH_FLAGS" -e "GIT_REMOTE_URL" -e "REVIEW_APP_NAME" -e "SSH_HOST_KEY" -e "SSH_PRIVATE_KEY" -e "TRACE" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true --entrypoint "/bin/dokku-deploy" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/opt/actions-runner/_work/_temp/_github_home":"/github/home" -v "/opt/actions-runner/_work/_temp/_github_workflow":"/github/workflow" -v "/opt/actions-runner/_work/_temp/_runner_file_commands":"/github/file_commands" -v "/opt/actions-runner/_work/chat-api/chat-api":"/github/workspace" 765292:81ac4e1e14194c3ba25c8d6c8bd6140d

Setting up SSH Key
+ '[' -n  ]
+ '[' -n  ]
+ '[' -n  ]
+ '[' -n  ]
+ '[' -n  ]
+ '[' -n  ]
+ '[' -n  ]
+ '[' -n  ]
+ '[' -z master ]
+ setup-ssh
+ '[' -n  ]
+ '[' -n  ]
+ log-info 'Setting up SSH Key'
+ mkdir -p /root/.ssh
+ tr -d '\r'
+ echo '***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***
***'
+ chmod 600 /root/.ssh/id_rsa
+ chmod 700 /root/.ssh
+ '[' -n '***' ]
+ log-info 'Adding SSH_HOST_KEY to known_hosts'
+ echo '***'
+ chmod 600 /root/.ssh/known_hosts
+ log-info 'Adding SSH Key to ssh-agent'

Adding SSH_HOST_KEY to known_hosts
+ ssh-agent -s

Adding SSH Key to ssh-agent
+ eval 'SSH_AUTH_SOCK=/tmp/ssh-XXXXXXeaAKiA/agent.17; export SSH_AUTH_SOCK;
SSH_AGENT_PID=18; export SSH_AGENT_PID;
echo Agent pid 18;'
+ SSH_AUTH_SOCK=/tmp/ssh-XXXXXXeaAKiA/agent.17
+ export SSH_AUTH_SOCK
+ SSH_AGENT_PID=18
+ export SSH_AGENT_PID
+ echo Agent pid 18
Agent pid 18
+ ssh-add /root/.ssh/id_rsa
Identity added: /root/.ssh/id_rsa (root@dlm)
+ parse-ci-commit
+ value=
+ '[' -n  ]
+ '[' -n  ]
+ '[' -n  ]
+ '[' -n  ]
+ '[' -n  ]
+ '[' -n ad9a9d8bd855e1ad54216df0edf644cfaace2475 ]
+ value=ad9a9d8bd855e1ad54216df0edf644cfaace2475
+ echo ad9a9d8bd855e1ad54216df0edf644cfaace2475
+ commit_sha=ad9a9d8bd855e1ad54216df0edf644cfaace2475
+ parse-app-name
+ '[' -n  ]
+ sed -e 's/.*\///'
+ echo ssh://dokku@dokku.mydomain.com:22/myapp-test
+ app_name=myapp-test
+ parse-ssh-host
+ '[' -n  ]
+ sed -e 's/.*@//' -e 's/[:/].*//'
+ echo ssh://dokku@dokku.mydomain.com:22/myapp-test
+ parse-ssh-port
+ '[' -n  ]
+ sed -e 's/.*@//' -e 's/\/.*//' -ne 's/.*:\([0-9]*\)/\1/p'
+ echo ssh://dokku@dokku.mydomain.com:22/myapp-test
+ ssh_port=2242
+ '[' -z 2242 ]
+ echo 2242
+ ssh_remote=ssh://dokku@dokku.mydomain.com:22
+ '[' deploy '=' review-apps:create ]
+ '[' deploy '=' review-apps:destroy ]
+ '[' deploy '=' review-apps:destroy ]
+ '[' -n deploy ]
+ '[' deploy '!=' review-apps:create ]
+ '[' deploy '!=' deploy ]
+ '[' -z ad9a9d8bd855e1ad54216df0edf644cfaace2475 ]
+ '[' deploy '=' review-apps:create ]
+ is_review_app=false
+ remote_app_name=myapp-test
+ '[' -n  ]
+ git config --global --add safe.directory /github/workspace
+ '[' -f bin/ci-pre-deploy ]
+ '[[' -f ci-commit-override ]]
+ '[' -n  ]
+ log-info 'Pushing to Dokku Host'

+ git push ssh://dokku@dokku.mydomain.com:22/myapp-test ad9a9d8bd855e1ad54216df0edf644cfaace2475:refs/heads/master
fatal: not a git repository (or any parent up to mount point /github)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Pushing to Dokku Host
```

</details>

**Comment by JKingas** [comment]
@josegonzalez 
I changed Actions to `actions/checkout@v3` and it works. Need to fix examples.

**Comment by josegonzalez** [comment]
I'm going to close this ticket. The original ticket was about host key verification, and we've gotten past that.

For the issue regarding the `~/`, please see the potential resolution in #15 [here](https://github.com/dokku/github-action/issues/15#issuecomment-1366920206).

@JKingas please file a new ticket for your issue, thats unrelated to either this ticket or the `~/` issue (though its the same that @danjac got).
