### ISSUE TITLE
feature request: comment on commits/prs and offloading github actions

### ISSUE THREAD

**Issue by vitordino** [dokku/github-action#9]
i was thinking on another way that should cut short the amount of time used on github actions..

i like the current way, and is the proper "github-actions" way.. but i’m afraid it will run out of github action minutes, while my server could actually do all the above, without depending much on github actions.

maybe the actions should just trigger some internal job that will comment the status of the build on the respective commit or pull request — so that the action would always run in a couple of seconds, and resulting on a "neutral" feedback on the action, or even drop all usage of github actions and just use something to watch for github repo changes.

maybe a new repo would be the better place to start sketching this, probably a `dokku plugin`

**Comment by josegonzalez** [comment]
It sounds like what you want is a webhook call, not a Github Action. I don't have any plans to do what you're suggesting, and I don't think it makes much sense from a developer feedback perspective (CI can run successfully but the deploy fails and then folks are stuck with questions about whether CI is even doing the right thing).

Dokku does not expose any webservice at this time, and there are no plans to do so for OSS. However, Dokku 0.23.0 introduced the [`git:sync`](http://dokku.viewdocs.io/dokku/deployment/methods/git/#initializing-an-app-repository-from-a-remote-repository) command that could be used to build such a thing.

Hope that helps. Feel free to join us on slack or [Discussions](https://github.com/dokku/dokku/discussions) with further questions/thoughts.

**Comment by vitordino** [comment]
thanks for the quick response.. yep, i will definitely read further on this..

and totally agree on the topics you pointed ✌️
